"""
Copyright (c) 2013 ICRL
See the file license.txt for copying permission.
"""

application: taintgameshub
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: taintgameshub.app